# Generated by Django 3.0.11 on 2020-11-09 22:07

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='name',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='react',
            name='detail',
        ),
        migrations.AddField(
            model_name='react',
            name='number',
            field=phone_field.models.PhoneField(blank=True, help_text='number', max_length=31),
        ),
    ]
