# Generated by Django 3.0.11 on 2020-11-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201109_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='message',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='react',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
